version: '3.8'
services:
  db:
    image: "postgres:12.11"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'
      TZ: Asia/Tokyo

    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app: &app
    build:
      context: .
      dockerfile: .
    image: takara/room-dashboard-api:1.0.0
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_data:/usr/local/bundle
    command: sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
    environment:
      TZ: Asia/Tokyo

  runner:
    <<: *app
    command: /bin/sh

volumes:
  postgres_volume:
  gem_data:
